config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'

  resources :up_files, only: [:index, :new, :create, :show] do
    member do
      post :download
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/up_file.rb
class UpFile < ApplicationRecord
  has_secure_password

  has_many_attached :files

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/up_files_controller.rb
class UpFilesController < ApplicationController
  def index
    @up_files = UpFile.all
  end

  def new
    @up_file = UpFile.new
  end

  def create
    @up_file = UpFile.new(up_file_params)
    if @up_file.save
      redirect_to up_file_path(@up_file, attention: true), notice: '保存したのだ'
    else
      render :new
    end
  end

  def show
    @up_file = UpFile.find(params[:id])
    @attention = params[:attention].present?
  end

  def download
    @up_file = UpFile.find(params[:id])
    unless @up_file.authenticate(params[:password])
      redirect_to up_file_path(@up_file), alert: 'パスワードが一致しませんでした'
    end
  end

  private def up_file_params
    params.require(:up_file).permit(:name, :password, :password_confirmation, files: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/up_files_helper.rb
module UpFilesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ActiveStrageSample
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |type, msg|
      %div{class: "alert alert-#{type}"}= msg
    = yield

app/views/top/index.html.haml
%h1 ようこそ

= link_to '新規登録', new_up_file_path

app/views/up_files/download.html.haml
%h1 ダウンロード
%ul
  - @up_file.files.each do |file|
    %li= link_to file.filename, rails_blob_path(file, disposition: 'attachment')

app/views/up_files/index.html.haml
%h1 一覧

%ul
  - @up_files.each do |up_file|
    %li= link_to up_file.name, up_file_path(up_file)

app/views/up_files/new.html.haml
- if @up_file.errors.present?
  %ul
    - @up_file.errors.full_messages.each do |message|
      %li= message

= form_with model: @up_file, local: true do |f|
  .field
    = f.label :name, '管理名'
    %br/
    = f.text_field :name

  .field
    = f.label :files, 'ファイル'
    %br/
    = f.file_field :files, multiple: true, direct_upload: true

  .field
    = f.label :password, 'パスワード'
    %br/
    = f.password_field :password

  .field
    = f.label :password_confirmation, 'パスワード再入力'
    %br/
    = f.password_field :password_confirmation

  .field
    = f.submit

app/views/up_files/show.html.haml
= link_to 'root', root_path

%h1= @up_file.name

- if @attention.present?
  %p このURLと設定したパスワードを伝えよう
  = up_file_url(@up_file)

%p アップロードファイル
%ul
  - @up_file.files.each do |file|
    %li
      = file.filename
      - if file.image?
        = image_tag file.variant(resize: "100x100")
      - elsif file.audio?
        = audio_tag rails_blob_url(file), controls: true

%p ダウンロード
= form_with url: download_up_file_path(@up_file), local: true do |f|
  .field
    = f.label :password, 'パスワード'
    %br/
    = f.text_field :password
  .field
    = f.submit 'ダウンロード'